#!/usr/bin/env bash

init_reporter() {
  REPORT_DIR="${REPORT_DIR:-reports/$(date +%Y%m%d-%H%M%S)}"
  mkdir -p "$REPORT_DIR"
  JSONL_FILE="$REPORT_DIR/results.jsonl"
  CSV_FILE="$REPORT_DIR/results.csv"
  SUMMARY_FILE="$REPORT_DIR/summary.txt"
  MARKDOWN_FILE="$REPORT_DIR/hackerone-findings.md"
  : > "$JSONL_FILE"
  printf 'timestamp,target,endpoint,status,classification,confidence,provider_hint,similarity,content_type,size_bytes,time_seconds,http_version,retries,location,reason,recommendation,body_sha256\n' > "$CSV_FILE"
}

append_json_result() {
  local file="$1"
  jq -c . "$file" >> "$JSONL_FILE"
  python3 - "$CSV_FILE" "$file" <<'PY'
import csv,json,sys
csv_path,json_path=sys.argv[1:]
r=json.load(open(json_path,encoding="utf-8"))
fields=["timestamp","target","endpoint","status","classification","confidence","provider_hint","similarity","content_type","size_bytes","time_seconds","http_version","retries","location","reason","recommendation","body_sha256"]
with open(csv_path,"a",newline="",encoding="utf-8") as f:
    csv.writer(f).writerow([r.get(k,"") for k in fields])
PY
}

classification_marker() {
  case "$1" in
    confirmed_exposure) printf '%bCONFIRMED%b' "$C_RED" "$C_RESET" ;;
    probable_exposure) printf '%bPROBABLE%b' "$C_YELLOW" "$C_RESET" ;;
    suspicious|custom_error) printf '%bREVIEW%b' "$C_YELLOW" "$C_RESET" ;;
    soft_404|spa_fallback|not_exposed) printf '%bNOT VALID%b' "$C_BLUE" "$C_RESET" ;;
    protected) printf '%bPROTECTED%b' "$C_GREEN" "$C_RESET" ;;
    waf_challenge) printf '%bWAF/CDN%b' "$C_YELLOW" "$C_RESET" ;;
    rate_limited) printf '%b429%b' "$C_YELLOW" "$C_RESET" ;;
    redirect_*) printf '%bREDIRECT%b' "$C_YELLOW" "$C_RESET" ;;
    upstream_error) printf '%b5XX%b' "$C_YELLOW" "$C_RESET" ;;
    network_error) printf '%bERROR%b' "$C_RED" "$C_RESET" ;;
    *) printf '%s' "$1" ;;
  esac
}

print_result_line() {
  local idx="$1" file="$2" status class confidence target endpoint reason marker
  status="$(jq -r '.status' "$file")"; class="$(jq -r '.classification' "$file")"
  confidence="$(jq -r '.confidence' "$file")"; target="$(jq -r '.target' "$file")"
  endpoint="$(jq -r '.endpoint' "$file")"; reason="$(jq -r '.reason' "$file")"
  marker="$(classification_marker "$class")"
  printf '[%03d] HTTP %-3s | %-12b | %3s%% | %s%s | %s\n' "$idx" "$status" "$marker" "$confidence" "$target" "$endpoint" "$reason"
}

build_markdown_report() {
  {
    printf '# Git Exposure Auditor — Candidate Findings\n\n'
    printf '> Generated by %s v%s. Manual validation is required before submission.\n\n' "$GEA_NAME" "$GEA_VERSION"
    printf '## Safety note\n\nNo repository dumping, credential testing, authentication/WAF bypass, brute force, or destructive action was performed. Response bodies were not retained.\n\n'
    local count
    count="$(jq -s '[.[]|select(.classification=="confirmed_exposure" or .classification=="probable_exposure")]|length' "$JSONL_FILE")"
    if [[ "$count" == "0" ]]; then
      printf '## Result\n\nNo confirmed or probable Git exposure was detected.\n'
      return 0
    fi
    jq -r -s '
      [.[]|select(.classification=="confirmed_exposure" or .classification=="probable_exposure")]
      | to_entries[]
      | "## Candidate \(.key+1): Publicly Accessible Git Metadata\n\n"
        + "**Affected asset:** `\(.value.target)`  \n"
        + "**Endpoint:** `\(.value.target)\(.value.endpoint)`  \n"
        + "**HTTP status:** `\(.value.status)`  \n"
        + "**Classification:** `\(.value.classification)`  \n"
        + "**Confidence:** `\(.value.confidence)/100`  \n"
        + "**Evidence hash:** `\(.value.body_sha256)`  \n"
        + "**Validation reason:** \(.value.reason)  \n\n"
        + "### Reproduction\n\n1. Send a GET request to the endpoint above.\n2. Confirm the response matches the described Git metadata signature.\n3. Compare against a random non-existent path to rule out soft-404 or SPA fallback behavior.\n\n"
        + "### Impact\n\nAccessible Git metadata can disclose repository structure, branch or commit references, and potentially sensitive development information. The actual impact depends on what the exposed repository contains.\n\n"
        + "### Remediation\n\nBlock `/.git` and all paths below it at the origin, reverse proxy, and CDN layers. Review repository history for secrets and rotate any exposed credentials.\n\n---\n"' "$JSONL_FILE"
  } > "$MARKDOWN_FILE"
}

build_summary() {
  local total
  total="$(jq -s 'length' "$JSONL_FILE")"
  {
    printf '%s v%s - Ringkasan\n' "$GEA_NAME" "$GEA_VERSION"
    printf 'Dibuat: %s\n\n' "$(date -Iseconds)"
    printf 'Total request: %s\n\n' "$total"
    printf 'Jumlah berdasarkan klasifikasi:\n'
    jq -r -s 'group_by(.classification)[] | "  \(.[0].classification): \(length) respons"' "$JSONL_FILE" | sort
    printf '\nJumlah berdasarkan HTTP status:\n'
    jq -r -s 'group_by(.status)[] | "  HTTP \(.[0].status): \(length) respons"' "$JSONL_FILE" | sort -V
    printf '\nJumlah berdasarkan provider hint:\n'
    jq -r -s 'group_by(.provider_hint)[] | "  \(.[0].provider_hint): \(length) respons"' "$JSONL_FILE" | sort
    printf '\nRekomendasi prioritas:\n'
    jq -r -s '.[] | select(.classification=="confirmed_exposure" or .classification=="probable_exposure" or .classification=="upstream_error") | "  - \(.target)\(.endpoint) [HTTP \(.status), \(.classification), \(.confidence)%]: \(.recommendation)"' "$JSONL_FILE"
  } | tee "$SUMMARY_FILE"

  build_markdown_report
  printf '\nLaporan:\n  JSONL   : %s\n  CSV     : %s\n  Ringkasan: %s\n  HackerOne: %s\n' "$JSONL_FILE" "$CSV_FILE" "$SUMMARY_FILE" "$MARKDOWN_FILE"
}
